/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.transaction.test.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.transaction.test.model.TransactionEntry;
import com.liferay.portal.transaction.test.model.TransactionEntryModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the TransactionEntry service. Represents a row in the &quot;TransactionEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>TransactionEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TransactionEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TransactionEntryImpl
 * @generated
 */
@ProviderType
public class TransactionEntryModelImpl
	extends BaseModelImpl<TransactionEntry> implements TransactionEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a transaction entry model instance should use the <code>TransactionEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "TransactionEntry";

	public static final Object[][] TABLE_COLUMNS = {
		{"transactionEntryId", Types.BIGINT}, {"value", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("transactionEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("value", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table TransactionEntry (transactionEntryId LONG not null primary key,value VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table TransactionEntry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY transactionEntry.transactionEntryId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY TransactionEntry.transactionEntryId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.portal.transaction.test.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.com.liferay.portal.transaction.test.model.TransactionEntry"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.portal.transaction.test.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.com.liferay.portal.transaction.test.model.TransactionEntry"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = false;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.portal.transaction.test.service.util.ServiceProps.get(
			"lock.expiration.time.com.liferay.portal.transaction.test.model.TransactionEntry"));

	public TransactionEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _transactionEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTransactionEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _transactionEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TransactionEntry.class;
	}

	@Override
	public String getModelClassName() {
		return TransactionEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<TransactionEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<TransactionEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TransactionEntry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((TransactionEntry)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<TransactionEntry, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<TransactionEntry, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(TransactionEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<TransactionEntry, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<TransactionEntry, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<TransactionEntry, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<TransactionEntry, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<TransactionEntry, Object>>
			attributeGetterFunctions =
				new LinkedHashMap<String, Function<TransactionEntry, Object>>();
		Map<String, BiConsumer<TransactionEntry, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<TransactionEntry, ?>>();

		attributeGetterFunctions.put(
			"transactionEntryId", TransactionEntry::getTransactionEntryId);
		attributeSetterBiConsumers.put(
			"transactionEntryId",
			(BiConsumer<TransactionEntry, Long>)
				TransactionEntry::setTransactionEntryId);
		attributeGetterFunctions.put("value", TransactionEntry::getValue);
		attributeSetterBiConsumers.put(
			"value",
			(BiConsumer<TransactionEntry, String>)TransactionEntry::setValue);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getTransactionEntryId() {
		return _transactionEntryId;
	}

	@Override
	public void setTransactionEntryId(long transactionEntryId) {
		_transactionEntryId = transactionEntryId;
	}

	@Override
	public String getValue() {
		if (_value == null) {
			return "";
		}
		else {
			return _value;
		}
	}

	@Override
	public void setValue(String value) {
		_value = value;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, TransactionEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TransactionEntry toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (TransactionEntry)ProxyUtil.newProxyInstance(
				_classLoader, _escapedModelInterfaces,
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TransactionEntryImpl transactionEntryImpl = new TransactionEntryImpl();

		transactionEntryImpl.setTransactionEntryId(getTransactionEntryId());
		transactionEntryImpl.setValue(getValue());

		transactionEntryImpl.resetOriginalValues();

		return transactionEntryImpl;
	}

	@Override
	public int compareTo(TransactionEntry transactionEntry) {
		long primaryKey = transactionEntry.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof TransactionEntry)) {
			return false;
		}

		TransactionEntry transactionEntry = (TransactionEntry)obj;

		long primaryKey = transactionEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<TransactionEntry> toCacheModel() {
		TransactionEntryCacheModel transactionEntryCacheModel =
			new TransactionEntryCacheModel();

		transactionEntryCacheModel.transactionEntryId = getTransactionEntryId();

		transactionEntryCacheModel.value = getValue();

		String value = transactionEntryCacheModel.value;

		if ((value != null) && (value.length() == 0)) {
			transactionEntryCacheModel.value = null;
		}

		return transactionEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<TransactionEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<TransactionEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TransactionEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((TransactionEntry)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<TransactionEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<TransactionEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TransactionEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((TransactionEntry)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader =
		TransactionEntry.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
		TransactionEntry.class, ModelWrapper.class
	};

	private long _transactionEntryId;
	private String _value;
	private TransactionEntry _escapedModel;

}