create index IX_C494F435 on BlogsEntry (ctCollectionId, companyId, uuid_[$COLUMN_LENGTH:75$]);
create unique index IX_25D369F2 on BlogsEntry (ctCollectionId, groupId, externalReferenceCode[$COLUMN_LENGTH:75$]);
create index IX_3D20502F on BlogsEntry (ctCollectionId, groupId, status, userId, displayDate);
create unique index IX_E83ED902 on BlogsEntry (ctCollectionId, groupId, urlTitle[$COLUMN_LENGTH:255$]);
create index IX_EDDFD649 on BlogsEntry (ctCollectionId, groupId, userId, displayDate);
create unique index IX_5BC5B9AF on BlogsEntry (ctCollectionId, groupId, uuid_[$COLUMN_LENGTH:75$]);
create index IX_1BC2FB67 on BlogsEntry (ctCollectionId, status, companyId, displayDate);
create index IX_1CC195E1 on BlogsEntry (ctCollectionId, status, displayDate);
create index IX_4CEDC7BF on BlogsEntry (ctCollectionId, status, userId, companyId);
create index IX_5E25DDD9 on BlogsEntry (ctCollectionId, userId, companyId);
create index IX_F1820C2F on BlogsEntry (ctCollectionId, uuid_[$COLUMN_LENGTH:75$]);