/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.service.base;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.CurrentConnectionUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.spring.extender.service.ServiceReference;
import com.liferay.portal.tools.service.builder.test.model.ArithmeticEntry;
import com.liferay.portal.tools.service.builder.test.service.ArithmeticEntryLocalService;
import com.liferay.portal.tools.service.builder.test.service.ArithmeticEntryLocalServiceUtil;
import com.liferay.portal.tools.service.builder.test.service.persistence.ArithmeticEntryPersistence;

import java.io.Serializable;

import java.sql.Connection;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the arithmetic entry local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.portal.tools.service.builder.test.service.impl.ArithmeticEntryLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.portal.tools.service.builder.test.service.impl.ArithmeticEntryLocalServiceImpl
 * @generated
 */
public abstract class ArithmeticEntryLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements ArithmeticEntryLocalService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>ArithmeticEntryLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>ArithmeticEntryLocalServiceUtil</code>.
	 */

	/**
	 * Adds the arithmetic entry to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ArithmeticEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param arithmeticEntry the arithmetic entry
	 * @return the arithmetic entry that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public ArithmeticEntry addArithmeticEntry(ArithmeticEntry arithmeticEntry) {
		arithmeticEntry.setNew(true);

		return arithmeticEntryPersistence.update(arithmeticEntry);
	}

	/**
	 * Creates a new arithmetic entry with the primary key. Does not add the arithmetic entry to the database.
	 *
	 * @param arithmeticEntryId the primary key for the new arithmetic entry
	 * @return the new arithmetic entry
	 */
	@Override
	@Transactional(enabled = false)
	public ArithmeticEntry createArithmeticEntry(long arithmeticEntryId) {
		return arithmeticEntryPersistence.create(arithmeticEntryId);
	}

	/**
	 * Deletes the arithmetic entry with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ArithmeticEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param arithmeticEntryId the primary key of the arithmetic entry
	 * @return the arithmetic entry that was removed
	 * @throws PortalException if a arithmetic entry with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public ArithmeticEntry deleteArithmeticEntry(long arithmeticEntryId)
		throws PortalException {

		return arithmeticEntryPersistence.remove(arithmeticEntryId);
	}

	/**
	 * Deletes the arithmetic entry from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ArithmeticEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param arithmeticEntry the arithmetic entry
	 * @return the arithmetic entry that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public ArithmeticEntry deleteArithmeticEntry(
		ArithmeticEntry arithmeticEntry) {

		return arithmeticEntryPersistence.remove(arithmeticEntry);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return arithmeticEntryPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			ArithmeticEntry.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return arithmeticEntryPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.tools.service.builder.test.model.impl.ArithmeticEntryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return arithmeticEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.tools.service.builder.test.model.impl.ArithmeticEntryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return arithmeticEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return arithmeticEntryPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return arithmeticEntryPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public ArithmeticEntry fetchArithmeticEntry(long arithmeticEntryId) {
		return arithmeticEntryPersistence.fetchByPrimaryKey(arithmeticEntryId);
	}

	/**
	 * Returns the arithmetic entry with the primary key.
	 *
	 * @param arithmeticEntryId the primary key of the arithmetic entry
	 * @return the arithmetic entry
	 * @throws PortalException if a arithmetic entry with the primary key could not be found
	 */
	@Override
	public ArithmeticEntry getArithmeticEntry(long arithmeticEntryId)
		throws PortalException {

		return arithmeticEntryPersistence.findByPrimaryKey(arithmeticEntryId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(arithmeticEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(ArithmeticEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("arithmeticEntryId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			arithmeticEntryLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(ArithmeticEntry.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"arithmeticEntryId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(arithmeticEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(ArithmeticEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("arithmeticEntryId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return arithmeticEntryPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement ArithmeticEntryLocalServiceImpl#deleteArithmeticEntry(ArithmeticEntry) to avoid orphaned data");
		}

		return arithmeticEntryLocalService.deleteArithmeticEntry(
			(ArithmeticEntry)persistedModel);
	}

	@Override
	public BasePersistence<ArithmeticEntry> getBasePersistence() {
		return arithmeticEntryPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return arithmeticEntryPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the arithmetic entries.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.tools.service.builder.test.model.impl.ArithmeticEntryModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of arithmetic entries
	 * @param end the upper bound of the range of arithmetic entries (not inclusive)
	 * @return the range of arithmetic entries
	 */
	@Override
	public List<ArithmeticEntry> getArithmeticEntries(int start, int end) {
		return arithmeticEntryPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of arithmetic entries.
	 *
	 * @return the number of arithmetic entries
	 */
	@Override
	public int getArithmeticEntriesCount() {
		return arithmeticEntryPersistence.countAll();
	}

	/**
	 * Updates the arithmetic entry in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ArithmeticEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param arithmeticEntry the arithmetic entry
	 * @return the arithmetic entry that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public ArithmeticEntry updateArithmeticEntry(
		ArithmeticEntry arithmeticEntry) {

		return arithmeticEntryPersistence.update(arithmeticEntry);
	}

	/**
	 * Returns the arithmetic entry local service.
	 *
	 * @return the arithmetic entry local service
	 */
	public ArithmeticEntryLocalService getArithmeticEntryLocalService() {
		return arithmeticEntryLocalService;
	}

	/**
	 * Sets the arithmetic entry local service.
	 *
	 * @param arithmeticEntryLocalService the arithmetic entry local service
	 */
	public void setArithmeticEntryLocalService(
		ArithmeticEntryLocalService arithmeticEntryLocalService) {

		this.arithmeticEntryLocalService = arithmeticEntryLocalService;
	}

	/**
	 * Returns the arithmetic entry persistence.
	 *
	 * @return the arithmetic entry persistence
	 */
	public ArithmeticEntryPersistence getArithmeticEntryPersistence() {
		return arithmeticEntryPersistence;
	}

	/**
	 * Sets the arithmetic entry persistence.
	 *
	 * @param arithmeticEntryPersistence the arithmetic entry persistence
	 */
	public void setArithmeticEntryPersistence(
		ArithmeticEntryPersistence arithmeticEntryPersistence) {

		this.arithmeticEntryPersistence = arithmeticEntryPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService
		getCounterLocalService() {

		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService
			counterLocalService) {

		this.counterLocalService = counterLocalService;
	}

	public void afterPropertiesSet() {
		ArithmeticEntryLocalServiceUtil.setService(arithmeticEntryLocalService);
	}

	public void destroy() {
		ArithmeticEntryLocalServiceUtil.setService(null);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return ArithmeticEntryLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return ArithmeticEntry.class;
	}

	protected String getModelClassName() {
		return ArithmeticEntry.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		DataSource dataSource = arithmeticEntryPersistence.getDataSource();

		DB db = DBManagerUtil.getDB();

		Connection currentConnection = CurrentConnectionUtil.getConnection(
			dataSource);

		try {
			if (currentConnection != null) {
				db.runSQL(currentConnection, new String[] {sql});

				return;
			}

			try (Connection connection = dataSource.getConnection()) {
				db.runSQL(connection, new String[] {sql});
			}
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@BeanReference(type = ArithmeticEntryLocalService.class)
	protected ArithmeticEntryLocalService arithmeticEntryLocalService;

	@BeanReference(type = ArithmeticEntryPersistence.class)
	protected ArithmeticEntryPersistence arithmeticEntryPersistence;

	@ServiceReference(
		type = com.liferay.counter.kernel.service.CounterLocalService.class
	)
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		ArithmeticEntryLocalServiceBaseImpl.class);

}