create index IX_A614C6D3 on KBArticle (ctCollectionId, companyId, uuid_[$COLUMN_LENGTH:75$]);
create index IX_6282D5B8 on KBArticle (ctCollectionId, groupId, kbFolderId, urlTitle[$COLUMN_LENGTH:75$]);
create index IX_9C4F8ED6 on KBArticle (ctCollectionId, groupId, latest, kbFolderId);
create index IX_1F2C059D on KBArticle (ctCollectionId, groupId, parentResourcePrimKey, main);
create index IX_1344D259 on KBArticle (ctCollectionId, groupId, resourcePrimKey, latest);
create index IX_C3FD84A7 on KBArticle (ctCollectionId, groupId, resourcePrimKey, main);
create index IX_C709221E on KBArticle (ctCollectionId, groupId, status, kbFolderId, urlTitle[$COLUMN_LENGTH:75$]);
create index IX_19C5B5 on KBArticle (ctCollectionId, groupId, status, latest, parentResourcePrimKey);
create index IX_18784350 on KBArticle (ctCollectionId, groupId, status, parentResourcePrimKey);
create index IX_B063361A on KBArticle (ctCollectionId, groupId, status, resourcePrimKey);
create unique index IX_F9B59BCD on KBArticle (ctCollectionId, groupId, uuid_[$COLUMN_LENGTH:75$]);
create unique index IX_1B3A37F8 on KBArticle (ctCollectionId, groupId, version, externalReferenceCode[$COLUMN_LENGTH:75$]);
create index IX_667A73FC on KBArticle (ctCollectionId, latest, companyId);
create index IX_D03C8E53 on KBArticle (ctCollectionId, latest, parentResourcePrimKey);
create index IX_38AB8A6E on KBArticle (ctCollectionId, main, companyId);
create index IX_126E1F21 on KBArticle (ctCollectionId, parentResourcePrimKey, main);
create index IX_8B784DDD on KBArticle (ctCollectionId, resourcePrimKey, latest);
create index IX_7322112B on KBArticle (ctCollectionId, resourcePrimKey, main);
create unique index IX_11C65A50 on KBArticle (ctCollectionId, resourcePrimKey, version);
create index IX_B2145A7 on KBArticle (ctCollectionId, status, companyId);
create index IX_B6A05683 on KBArticle (ctCollectionId, status, displayDate);
create index IX_439A0BD4 on KBArticle (ctCollectionId, status, parentResourcePrimKey);
create index IX_2896B19E on KBArticle (ctCollectionId, status, resourcePrimKey);
create index IX_F7EBB051 on KBArticle (ctCollectionId, uuid_[$COLUMN_LENGTH:75$]);

create index IX_B293A0E7 on KBComment (ctCollectionId, classNameId, classPK, status);
create index IX_5412BA3B on KBComment (ctCollectionId, classNameId, classPK, userId);
create index IX_373956CC on KBComment (ctCollectionId, classNameId, groupId);
create index IX_10606DE4 on KBComment (ctCollectionId, groupId, status);
create unique index IX_2A6122F6 on KBComment (ctCollectionId, groupId, uuid_[$COLUMN_LENGTH:75$]);
create index IX_59FB27BC on KBComment (ctCollectionId, uuid_[$COLUMN_LENGTH:75$], companyId);

create unique index IX_A903BB96 on KBFolder (ctCollectionId, groupId, externalReferenceCode[$COLUMN_LENGTH:75$]);
create index IX_FF96397E on KBFolder (ctCollectionId, groupId, parentKBFolderId, name[$COLUMN_LENGTH:75$]);
create index IX_A0D6EC5C on KBFolder (ctCollectionId, groupId, parentKBFolderId, urlTitle[$COLUMN_LENGTH:75$]);
create unique index IX_FB75D353 on KBFolder (ctCollectionId, groupId, uuid_[$COLUMN_LENGTH:75$]);
create index IX_38A534D9 on KBFolder (ctCollectionId, uuid_[$COLUMN_LENGTH:75$], companyId);

create index IX_A4B97D25 on KBTemplate (ctCollectionId, uuid_[$COLUMN_LENGTH:75$], companyId);
create unique index IX_1857BE9F on KBTemplate (ctCollectionId, uuid_[$COLUMN_LENGTH:75$], groupId);