/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.model;

import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ArithmeticEntry service. Represents a row in the &quot;ArithmeticEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.portal.tools.service.builder.test.model.impl.ArithmeticEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.portal.tools.service.builder.test.model.impl.ArithmeticEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ArithmeticEntry
 * @generated
 */
@ProviderType
public interface ArithmeticEntryModel extends BaseModel<ArithmeticEntry> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a arithmetic entry model instance should use the {@link ArithmeticEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this arithmetic entry.
	 *
	 * @return the primary key of this arithmetic entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this arithmetic entry.
	 *
	 * @param primaryKey the primary key of this arithmetic entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the arithmetic entry ID of this arithmetic entry.
	 *
	 * @return the arithmetic entry ID of this arithmetic entry
	 */
	public long getArithmeticEntryId();

	/**
	 * Sets the arithmetic entry ID of this arithmetic entry.
	 *
	 * @param arithmeticEntryId the arithmetic entry ID of this arithmetic entry
	 */
	public void setArithmeticEntryId(long arithmeticEntryId);

	/**
	 * Returns the number1 of this arithmetic entry.
	 *
	 * @return the number1 of this arithmetic entry
	 */
	public long getNumber1();

	/**
	 * Sets the number1 of this arithmetic entry.
	 *
	 * @param number1 the number1 of this arithmetic entry
	 */
	public void setNumber1(long number1);

	/**
	 * Returns the number2 of this arithmetic entry.
	 *
	 * @return the number2 of this arithmetic entry
	 */
	public long getNumber2();

	/**
	 * Sets the number2 of this arithmetic entry.
	 *
	 * @param number2 the number2 of this arithmetic entry
	 */
	public void setNumber2(long number2);

	@Override
	public ArithmeticEntry cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}