/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.tools.service.builder.test.model;

import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the NotCachedEntry service. Represents a row in the &quot;NotCachedEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.portal.tools.service.builder.test.model.impl.NotCachedEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.portal.tools.service.builder.test.model.impl.NotCachedEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see NotCachedEntry
 * @generated
 */
@ProviderType
public interface NotCachedEntryModel extends BaseModel<NotCachedEntry> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a not cached entry model instance should use the {@link NotCachedEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this not cached entry.
	 *
	 * @return the primary key of this not cached entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this not cached entry.
	 *
	 * @param primaryKey the primary key of this not cached entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the nested sets tree entry ID of this not cached entry.
	 *
	 * @return the nested sets tree entry ID of this not cached entry
	 */
	public long getNestedSetsTreeEntryId();

	/**
	 * Sets the nested sets tree entry ID of this not cached entry.
	 *
	 * @param nestedSetsTreeEntryId the nested sets tree entry ID of this not cached entry
	 */
	public void setNestedSetsTreeEntryId(long nestedSetsTreeEntryId);

	/**
	 * Returns the column1 of this not cached entry.
	 *
	 * @return the column1 of this not cached entry
	 */
	public long getColumn1();

	/**
	 * Sets the column1 of this not cached entry.
	 *
	 * @param column1 the column1 of this not cached entry
	 */
	public void setColumn1(long column1);

	/**
	 * Returns the column2 of this not cached entry.
	 *
	 * @return the column2 of this not cached entry
	 */
	public long getColumn2();

	/**
	 * Sets the column2 of this not cached entry.
	 *
	 * @param column2 the column2 of this not cached entry
	 */
	public void setColumn2(long column2);

}