/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.osgi.web.servlet.jsp.compiler.internal;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.CharArrayWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.io.UnsupportedEncodingException;
import java.io.Writer;

import java.net.URI;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;

import javax.tools.Diagnostic;
import javax.tools.DiagnosticCollector;
import javax.tools.FileObject;
import javax.tools.ForwardingJavaFileManager;
import javax.tools.JavaFileManager;
import javax.tools.JavaFileObject;
import javax.tools.SimpleJavaFileObject;
import javax.tools.StandardLocation;
import javax.tools.ToolProvider;

import org.apache.jasper.Constants;
import org.apache.jasper.JasperException;
import org.apache.jasper.JspCompilationContext;
import org.apache.jasper.Options;
import org.apache.jasper.compiler.ErrorDispatcher;
import org.apache.jasper.compiler.JavaCompiler;
import org.apache.jasper.compiler.JavacErrorDetail;
import org.apache.jasper.compiler.JspRuntimeContext;
import org.apache.jasper.compiler.Node;

/**
 * Invoke Java Compiler per JSR 199, using in-memory storage for both the
 * input Java source and the generated bytecodes.
 *
 * @author Kin-man Chung
 */
public class Jsr199JavaCompiler implements JavaCompiler {

	@Override
	public JavacErrorDetail[] compile(String className, Node.Nodes pageNodes)
		throws JasperException {

		classFiles = new ArrayList<>();

		if (ToolProvider.getSystemJavaCompiler() == null) {
			errorDispatcher.jspError("jsp.error.nojdk");

			throw new JasperException("Unable to find Java compiler");
		}

		DiagnosticCollector<JavaFileObject> diagnosticCollector =
			new DiagnosticCollector<>();

		try {
			if (_jspCompiler.compile(
				className, charArrayWriter.toString(), compilerOptions,
				diagnosticCollector,
				javaFileManager -> getJavaFileManager(javaFileManager))) {

				for (BytecodeFile bytecodeFile : classFiles) {
					jspRuntimeContext.setBytecode(
						bytecodeFile.getClassName(),
						bytecodeFile.getBytecode());
				}

				return null;
			}
		}
		catch (IOException ioe) {
			throw new JasperException(ioe);
		}

		List<Diagnostic<? extends JavaFileObject>> diagnostics =
			diagnosticCollector.getDiagnostics();

		JavacErrorDetail[] javacErrorDetails =
			new JavacErrorDetail[diagnostics.size()];

		for (int i = 0; i < diagnostics.size(); i++) {
			Diagnostic<? extends JavaFileObject> diagnostic = diagnostics.get(
				i);

			javacErrorDetails[i] = ErrorDispatcher.createJavacError(
				javaFileName, pageNodes,
				new StringBuilder(diagnostic.getMessage(null)),
				(int)diagnostic.getLineNumber());
		}

		return javacErrorDetails;
	}

	public void doJavaFile(boolean keep) throws JasperException {
		if (!keep) {
			charArrayWriter = null;

			return;
		}

		try (Writer writer = new OutputStreamWriter(
				new FileOutputStream(javaFileName), javaEncoding)) {

			writer.write(charArrayWriter.toString());

			charArrayWriter = null;
		}
		catch (UnsupportedEncodingException uee) {
			errorDispatcher.jspError(
				"jsp.error.needAlternateJavaEncoding", javaEncoding);
		}
		catch (IOException ioe) {
			throw new JasperException(ioe);
		}
	}

	public long getClassLastModified() {
		String className = _jspCompilationContext.getFullClassName();

		return jspRuntimeContext.getBytecodeBirthTime(className);
	}

	// a JSP compilation can produce multiple class files, we need to
	// keep track of all generated bytecodes..

	public Writer getJavaWriter(String javaFileName, String javaEncoding) {
		this.javaFileName = javaFileName;
		this.javaEncoding = javaEncoding;

		charArrayWriter = new CharArrayWriter();

		return charArrayWriter;
	}

	public void init(
		JspCompilationContext jspCompilationContext,
		ErrorDispatcher errorDispatcher, boolean suppressLogging) {

		Options options = jspCompilationContext.getOptions();

		_jspCompiler.init(jspCompilationContext, options.getScratchDir());

		_jspCompilationContext = jspCompilationContext;

		this.errorDispatcher = errorDispatcher;

		jspRuntimeContext = jspCompilationContext.getRuntimeContext();

		// Disable annotation processing

		compilerOptions.add("-proc:none");
	}

	public void release() {

		// release temp bytecodes

		classFiles = null;
	}

	public void saveClassFile(String className, String classFileName) {
		for (BytecodeFile bytecodeFile : classFiles) {
			String bytecodeFileClassName = bytecodeFile.getClassName();
			String fileName = classFileName;

			if (!className.equals(bytecodeFileClassName)) {

				// Compute inner class file name

				fileName = fileName.substring(
					0, fileName.lastIndexOf(File.separator) + 1);

				fileName = fileName.concat(
					bytecodeFileClassName.substring(
						bytecodeFileClassName.lastIndexOf('.') + 1)
				).concat(
					".class"
				);
			}

			jspRuntimeContext.saveBytecode(bytecodeFileClassName, fileName);
		}
	}

	public void setClassPath(List<File> classPath) {
		this.classPath = classPath;
	}

	public void setDebug(boolean debug) {
		if (debug) {
			compilerOptions.add("-g");
		}
		else {
			compilerOptions.add("-g:none");
		}
	}

	public void setExtdirs(String extdirs) {
		compilerOptions.add("-extdirs");
		compilerOptions.add(extdirs);
	}

	public void setSourceVM(String sourceVM) {
		compilerOptions.add("-source");
		compilerOptions.add(sourceVM);
	}

	public void setTargetVM(String targetVM) {
		compilerOptions.add("-target");
		compilerOptions.add(targetVM);
	}

	public static class BytecodeFile extends SimpleJavaFileObject {

		public BytecodeFile(URI uri, String className) {
			super(uri, JavaFileObject.Kind.CLASS);

			_className = className;
		}

		public byte[] getBytecode() {
			return _bytecode;
		}

		public String getClassName() {
			return _className;
		}

		public InputStream openInputStream() {
			return new ByteArrayInputStream(_bytecode);
		}

		public OutputStream openOutputStream() {
			return new ByteArrayOutputStream() {

				public void close() {
					_bytecode = toByteArray();
				}

			};
		}

		private byte[] _bytecode;
		private final String _className;

	}

	protected JavaFileManager getJavaFileManager(JavaFileManager fm) {
		return new ForwardingJavaFileManager<JavaFileManager>(fm) {

			@Override
			public JavaFileObject getJavaFileForOutput(
				JavaFileManager.Location location, String className,
				JavaFileObject.Kind kind, FileObject sibling) {

				return getOutputFile(
					className,
					URI.create(
						"file:///" + className.replace('.', '/') + kind));
			}

			@Override
			public String inferBinaryName(
				JavaFileManager.Location location, JavaFileObject file) {

				if (file instanceof BytecodeFile) {
					return ((BytecodeFile)file).getClassName();
				}

				return super.inferBinaryName(location, file);
			}

			@Override
			public Iterable<JavaFileObject> list(
					JavaFileManager.Location location, String packageName,
					Set<JavaFileObject.Kind> kinds, boolean recurse)
				throws IOException {

				if ((location == StandardLocation.CLASS_PATH) &&
					packageName.startsWith(Constants.JSP_PACKAGE_NAME)) {

					// TODO: Need to handle the case where some of the classes
					// are on disk

					Map<String, Map<String, JavaFileObject>> packageMap =
						jspRuntimeContext.getPackageMap();

					Map<String, JavaFileObject> packageFiles = packageMap.get(
						packageName);

					if (packageFiles != null) {
						return packageFiles.values();
					}
				}

				Iterable<JavaFileObject> javaFileObjects = super.list(
					location, packageName, kinds, recurse);

				return javaFileObjects;
			}

		};
	}

	protected JavaFileObject getOutputFile(String className, URI uri) {
		BytecodeFile bytecodeFile = new BytecodeFile(uri, className);

		// File the class file away, by its package name

		String packageName = className.substring(0, className.lastIndexOf("."));

		Map<String, Map<String, JavaFileObject>> packageMap =
			jspRuntimeContext.getPackageMap();

		Map<String, JavaFileObject> packageJavaFileObjects = packageMap.get(
			packageName);

		if (packageJavaFileObjects == null) {
			packageJavaFileObjects = new ConcurrentHashMap<>();

			packageMap.put(packageName, packageJavaFileObjects);
		}

		packageJavaFileObjects.put(className, bytecodeFile);

		classFiles.add(bytecodeFile);

		return bytecodeFile;
	}

	protected CharArrayWriter charArrayWriter;
	protected List<BytecodeFile> classFiles;
	protected List<File> classPath;
	protected ErrorDispatcher errorDispatcher;
	protected String javaEncoding;
	protected String javaFileName;
	protected JspRuntimeContext jspRuntimeContext;
	protected List<String> compilerOptions = new ArrayList<>();

	private JspCompilationContext _jspCompilationContext;
	private final JspCompiler _jspCompiler = new JspCompiler();

}