/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.osgi.web.servlet.jsp.compiler.internal;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.CharArrayWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.io.UnsupportedEncodingException;
import java.io.Writer;

import java.net.URI;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

import javax.tools.Diagnostic;
import javax.tools.DiagnosticCollector;
import javax.tools.FileObject;
import javax.tools.ForwardingJavaFileManager;
import javax.tools.JavaFileManager;
import javax.tools.JavaFileObject;
import javax.tools.SimpleJavaFileObject;
import javax.tools.StandardJavaFileManager;
import javax.tools.StandardLocation;
import javax.tools.ToolProvider;

import org.apache.jasper.Constants;
import org.apache.jasper.JasperException;
import org.apache.jasper.JspCompilationContext;
import org.apache.jasper.compiler.ErrorDispatcher;
import org.apache.jasper.compiler.JavaCompiler;
import org.apache.jasper.compiler.JavacErrorDetail;
import org.apache.jasper.compiler.JspRuntimeContext;
import org.apache.jasper.compiler.JspUtil;
import org.apache.jasper.compiler.Node;

/**
 * Invoke Java Compiler per JSR 199, using in-memory storage for both the
 * input Java source and the generated bytecodes.
 *
 * @author Kin-man Chung
 */
public class Jsr199JavaCompiler implements JavaCompiler {

	public JavacErrorDetail[] compile(String className, Node.Nodes pageNodes)
		throws JasperException {

		final String source = charArrayWriter.toString();
		classFiles = new ArrayList<>();

		javax.tools.JavaCompiler javac = ToolProvider.getSystemJavaCompiler();

		if (javac == null) {
			errDispatcher.jspError("jsp.error.nojdk");
		}

		DiagnosticCollector<JavaFileObject> diagnostics =
			new DiagnosticCollector<>();

		StandardJavaFileManager stdFileManager = javac.getStandardFileManager(
			diagnostics, null, null);

		String name = className.substring(className.lastIndexOf('.') + 1);

		JavaFileObject[] sourceFiles = {
			new SimpleJavaFileObject(
				URI.create(
					"string:///" + name.replace('.', '/') +
						JavaFileObject.Kind.SOURCE.extension),
				JavaFileObject.Kind.SOURCE) {

				public CharSequence getCharContent(boolean ignore) {
					return source;
				}

			}
		};

		try {
			stdFileManager.setLocation(StandardLocation.CLASS_PATH, cpath);
		}
		catch (IOException ioe) {
		}

		JavaFileManager javaFileManager = getJavaFileManager(stdFileManager);

		javax.tools.JavaCompiler.CompilationTask ct = javac.getTask(
			null, javaFileManager, diagnostics, options, null,
			Arrays.asList(sourceFiles));

		try {
			javaFileManager.close();
		}
		catch (IOException ioe) {
		}

		if (ct.call()) {
			for (BytecodeFile bytecodeFile : classFiles) {
				rtctxt.setBytecode(
					bytecodeFile.getClassName(), bytecodeFile.getBytecode());
			}

			return null;
		}

		// There are compilation errors!

		ArrayList<JavacErrorDetail> problems = new ArrayList<>();

		for (Diagnostic dm : diagnostics.getDiagnostics()) {
			problems.add(
				ErrorDispatcher.createJavacError(
					javaFileName, pageNodes,
					new StringBuilder(dm.getMessage(null)),
					(int)dm.getLineNumber()));
		}

		return problems.toArray(new JavacErrorDetail[0]);
	}

	public void doJavaFile(boolean keep) throws JasperException {
		if (!keep) {
			charArrayWriter = null;

			return;
		}

		try {
			Writer writer = new OutputStreamWriter(
				new FileOutputStream(javaFileName), javaEncoding);

			writer.write(charArrayWriter.toString());

			writer.close();

			charArrayWriter = null;
		}
		catch (UnsupportedEncodingException uee) {
			errDispatcher.jspError(
				"jsp.error.needAlternateJavaEncoding", javaEncoding);
		}
		catch (IOException ioe) {
			throw new JasperException(ioe);
		}
	}

	public long getClassLastModified() {
		String className = _ctxt.getFullClassName();

		return rtctxt.getBytecodeBirthTime(className);
	}

	// a JSP compilation can produce multiple class files, we need to
	// keep track of all generated bytecodes..

	public Writer getJavaWriter(String javaFileName, String javaEncoding) {
		this.javaFileName = javaFileName;
		this.javaEncoding = javaEncoding;

		charArrayWriter = new CharArrayWriter();

		return charArrayWriter;
	}

	public void init(
		JspCompilationContext ctxt, ErrorDispatcher errDispatcher,
		boolean suppressLogging) {

		_ctxt = ctxt;

		this.errDispatcher = errDispatcher;

		rtctxt = ctxt.getRuntimeContext();

		// Disable annotation processing

		options.add("-proc:none");
	}

	public void release() {

		// release temp bytecodes

		classFiles = null;
	}

	public void saveClassFile(String className, String classFileName) {
		for (BytecodeFile bytecodeFile : classFiles) {
			String c = bytecodeFile.getClassName();
			String f = classFileName;

			if (!className.equals(c)) {

				// Compute inner class file name

				f =
					f.substring(0, f.lastIndexOf(File.separator) + 1) +
						c.substring(c.lastIndexOf('.') + 1) + ".class";
			}

			rtctxt.saveBytecode(c, f);
		}
	}

	public void setClassPath(List<File> path) {

		// Jsr199 does not expand jar manifest Class-Path (JDK bug?), we
		// need to do it here

		List<String> paths = new ArrayList<>();

		for (File f : path) {
			paths.add(f.toString());
		}

		List<String> files = JspUtil.expandClassPath(paths);

		cpath = new ArrayList<>();

		for (String file : files) {
			cpath.add(new File(file));
		}
	}

	public void setDebug(boolean debug) {
		if (debug) {
			options.add("-g");
		}
		else {
			options.add("-g:none");
		}
	}

	public void setExtdirs(String exts) {
		options.add("-extdirs");
		options.add(exts);
	}

	public void setSourceVM(String sourceVM) {
		options.add("-source");
		options.add(sourceVM);
	}

	public void setTargetVM(String targetVM) {
		options.add("-target");
		options.add(targetVM);
	}

	public static class BytecodeFile extends SimpleJavaFileObject {

		public BytecodeFile(URI uri, String className) {
			super(uri, JavaFileObject.Kind.CLASS);

			_className = className;
		}

		public byte[] getBytecode() {
			return _bytecode;
		}

		public String getClassName() {
			return _className;
		}

		public InputStream openInputStream() {
			return new ByteArrayInputStream(_bytecode);
		}

		public OutputStream openOutputStream() {
			return new ByteArrayOutputStream() {

				public void close() {
					_bytecode = toByteArray();
				}

			};
		}

		private byte[] _bytecode;
		private final String _className;

	}

	protected JavaFileManager getJavaFileManager(JavaFileManager fm) {
		return new ForwardingJavaFileManager<JavaFileManager>(fm) {

			@Override
			public JavaFileObject getJavaFileForOutput(
				JavaFileManager.Location location, String className,
				JavaFileObject.Kind kind, FileObject sibling) {

				return getOutputFile(
					className,
					URI.create(
						"file:///" + className.replace('.', '/') + kind));
			}

			@Override
			public String inferBinaryName(
				JavaFileManager.Location location, JavaFileObject file) {

				if (file instanceof BytecodeFile) {
					return ((BytecodeFile)file).getClassName();
				}

				return super.inferBinaryName(location, file);
			}

			@Override
			public Iterable<JavaFileObject> list(
					JavaFileManager.Location location, String packageName,
					Set<JavaFileObject.Kind> kinds, boolean recurse)
				throws IOException {

				if ((location == StandardLocation.CLASS_PATH) &&
					packageName.startsWith(Constants.JSP_PACKAGE_NAME)) {

					// TODO: Need to handle the case where some of the classes
					// are on disk

					Map<String, Map<String, JavaFileObject>> packageMap =
						rtctxt.getPackageMap();

					Map<String, JavaFileObject> packageFiles = packageMap.get(
						packageName);

					if (packageFiles != null) {
						return packageFiles.values();
					}
				}

				Iterable<JavaFileObject> lst = super.list(
					location, packageName, kinds, recurse);

				return lst;
			}

		};
	}

	protected JavaFileObject getOutputFile(String className, URI uri) {
		BytecodeFile classFile = new BytecodeFile(uri, className);

		// File the class file away, by its package name

		String packageName = className.substring(0, className.lastIndexOf("."));

		Map<String, Map<String, JavaFileObject>> packageMap =
			rtctxt.getPackageMap();

		Map<String, JavaFileObject> packageFiles = packageMap.get(packageName);

		if (packageFiles == null) {
			packageFiles = new HashMap<>();

			packageMap.put(packageName, packageFiles);
		}

		packageFiles.put(className, classFile);

		classFiles.add(classFile);

		return classFile;
	}

	protected CharArrayWriter charArrayWriter;
	protected ArrayList<BytecodeFile> classFiles;
	protected List<File> cpath;
	protected ErrorDispatcher errDispatcher;
	protected String javaEncoding;
	protected String javaFileName;
	protected ArrayList<String> options = new ArrayList<>();
	protected JspRuntimeContext rtctxt;

	private JspCompilationContext _ctxt;

}