/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.transaction.test.service.base;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;
import com.liferay.portal.transaction.test.model.TransactionEntry;
import com.liferay.portal.transaction.test.service.TransactionEntryLocalService;
import com.liferay.portal.transaction.test.service.persistence.TransactionEntryPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the transaction entry local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.portal.transaction.test.service.impl.TransactionEntryLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.portal.transaction.test.service.impl.TransactionEntryLocalServiceImpl
 * @generated
 */
@ProviderType
public abstract class TransactionEntryLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements TransactionEntryLocalService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>TransactionEntryLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.liferay.portal.transaction.test.service.TransactionEntryLocalServiceUtil</code>.
	 */

	/**
	 * Adds the transaction entry to the database. Also notifies the appropriate model listeners.
	 *
	 * @param transactionEntry the transaction entry
	 * @return the transaction entry that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public TransactionEntry addTransactionEntry(
		TransactionEntry transactionEntry) {

		transactionEntry.setNew(true);

		return transactionEntryPersistence.update(transactionEntry);
	}

	/**
	 * Creates a new transaction entry with the primary key. Does not add the transaction entry to the database.
	 *
	 * @param transactionEntryId the primary key for the new transaction entry
	 * @return the new transaction entry
	 */
	@Override
	@Transactional(enabled = false)
	public TransactionEntry createTransactionEntry(long transactionEntryId) {
		return transactionEntryPersistence.create(transactionEntryId);
	}

	/**
	 * Deletes the transaction entry with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param transactionEntryId the primary key of the transaction entry
	 * @return the transaction entry that was removed
	 * @throws PortalException if a transaction entry with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public TransactionEntry deleteTransactionEntry(long transactionEntryId)
		throws PortalException {

		return transactionEntryPersistence.remove(transactionEntryId);
	}

	/**
	 * Deletes the transaction entry from the database. Also notifies the appropriate model listeners.
	 *
	 * @param transactionEntry the transaction entry
	 * @return the transaction entry that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public TransactionEntry deleteTransactionEntry(
		TransactionEntry transactionEntry) {

		return transactionEntryPersistence.remove(transactionEntry);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			TransactionEntry.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return transactionEntryPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code>), then the query will include the default ORDER BY logic from <code>com.liferay.portal.transaction.test.model.impl.TransactionEntryModelImpl</code>. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return transactionEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code>), then the query will include the default ORDER BY logic from <code>com.liferay.portal.transaction.test.model.impl.TransactionEntryModelImpl</code>. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return transactionEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return transactionEntryPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return transactionEntryPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public TransactionEntry fetchTransactionEntry(long transactionEntryId) {
		return transactionEntryPersistence.fetchByPrimaryKey(
			transactionEntryId);
	}

	/**
	 * Returns the transaction entry with the primary key.
	 *
	 * @param transactionEntryId the primary key of the transaction entry
	 * @return the transaction entry
	 * @throws PortalException if a transaction entry with the primary key could not be found
	 */
	@Override
	public TransactionEntry getTransactionEntry(long transactionEntryId)
		throws PortalException {

		return transactionEntryPersistence.findByPrimaryKey(transactionEntryId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			transactionEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(TransactionEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("transactionEntryId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			transactionEntryLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(TransactionEntry.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"transactionEntryId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			transactionEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(TransactionEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("transactionEntryId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return transactionEntryLocalService.deleteTransactionEntry(
			(TransactionEntry)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return transactionEntryPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the transaction entries.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code>), then the query will include the default ORDER BY logic from <code>com.liferay.portal.transaction.test.model.impl.TransactionEntryModelImpl</code>. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of transaction entries
	 * @param end the upper bound of the range of transaction entries (not inclusive)
	 * @return the range of transaction entries
	 */
	@Override
	public List<TransactionEntry> getTransactionEntries(int start, int end) {
		return transactionEntryPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of transaction entries.
	 *
	 * @return the number of transaction entries
	 */
	@Override
	public int getTransactionEntriesCount() {
		return transactionEntryPersistence.countAll();
	}

	/**
	 * Updates the transaction entry in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param transactionEntry the transaction entry
	 * @return the transaction entry that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public TransactionEntry updateTransactionEntry(
		TransactionEntry transactionEntry) {

		return transactionEntryPersistence.update(transactionEntry);
	}

	/**
	 * Returns the transaction entry local service.
	 *
	 * @return the transaction entry local service
	 */
	public TransactionEntryLocalService getTransactionEntryLocalService() {
		return transactionEntryLocalService;
	}

	/**
	 * Sets the transaction entry local service.
	 *
	 * @param transactionEntryLocalService the transaction entry local service
	 */
	public void setTransactionEntryLocalService(
		TransactionEntryLocalService transactionEntryLocalService) {

		this.transactionEntryLocalService = transactionEntryLocalService;
	}

	/**
	 * Returns the transaction entry persistence.
	 *
	 * @return the transaction entry persistence
	 */
	public TransactionEntryPersistence getTransactionEntryPersistence() {
		return transactionEntryPersistence;
	}

	/**
	 * Sets the transaction entry persistence.
	 *
	 * @param transactionEntryPersistence the transaction entry persistence
	 */
	public void setTransactionEntryPersistence(
		TransactionEntryPersistence transactionEntryPersistence) {

		this.transactionEntryPersistence = transactionEntryPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService
		getCounterLocalService() {

		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService
			counterLocalService) {

		this.counterLocalService = counterLocalService;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register(
			"com.liferay.portal.transaction.test.model.TransactionEntry",
			transactionEntryLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"com.liferay.portal.transaction.test.model.TransactionEntry");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return TransactionEntryLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return TransactionEntry.class;
	}

	protected String getModelClassName() {
		return TransactionEntry.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = transactionEntryPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = TransactionEntryLocalService.class)
	protected TransactionEntryLocalService transactionEntryLocalService;

	@BeanReference(type = TransactionEntryPersistence.class)
	protected TransactionEntryPersistence transactionEntryPersistence;

	@ServiceReference(
		type = com.liferay.counter.kernel.service.CounterLocalService.class
	)
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry
		persistedModelLocalServiceRegistry;

}