sourceCompatibility = "1.6"
targetCompatibility = "1.6"

dependencies {
	compile group: "com.liferay", name: "com.liferay.portal.osgi.web.servlet.jsp.compiler", version: "5.0.0"
	compile group: "javax.servlet.jsp", name: "javax.servlet.jsp-api", version: "2.3.2-b01"
	compile group: "org.apache.ant", name: "ant", version: "1.9.14"

	compileOnly group: "org.glassfish", name: "javax.servlet", version: "3.2-b06"
}

liferay {
	deployDir = "../../../tools/sdk/dependencies/com.liferay.jasper.jspc/lib"
}

updateFileVersions {
	match(/com\.liferay\.jasper\.jspc=(\d.+)/, "../../sdk/gradle-plugins/src/main/resources/com/liferay/gradle/plugins/dependencies/portal-tools.properties")
}