/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.transaction.test.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

/**
 * The base model interface for the TransactionEntry service. Represents a row in the &quot;TransactionEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.portal.transaction.test.model.impl.TransactionEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.portal.transaction.test.model.impl.TransactionEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TransactionEntry
 * @generated
 */
@ProviderType
public interface TransactionEntryModel extends BaseModel<TransactionEntry> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a transaction entry model instance should use the {@link TransactionEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this transaction entry.
	 *
	 * @return the primary key of this transaction entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this transaction entry.
	 *
	 * @param primaryKey the primary key of this transaction entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the transaction entry ID of this transaction entry.
	 *
	 * @return the transaction entry ID of this transaction entry
	 */
	public long getTransactionEntryId();

	/**
	 * Sets the transaction entry ID of this transaction entry.
	 *
	 * @param transactionEntryId the transaction entry ID of this transaction entry
	 */
	public void setTransactionEntryId(long transactionEntryId);

	/**
	 * Returns the value of this transaction entry.
	 *
	 * @return the value of this transaction entry
	 */
	@AutoEscape
	public String getValue();

	/**
	 * Sets the value of this transaction entry.
	 *
	 * @param value the value of this transaction entry
	 */
	public void setValue(String value);

}