create index IX_3B92EB34 on WikiNode (ctCollectionId, companyId, status);
create unique index IX_98F1D7A3 on WikiNode (ctCollectionId, groupId, externalReferenceCode[$COLUMN_LENGTH:75$]);
create unique index IX_384A2A93 on WikiNode (ctCollectionId, groupId, name[$COLUMN_LENGTH:75$]);
create index IX_2F62B4BA on WikiNode (ctCollectionId, groupId, status);
create unique index IX_652FA960 on WikiNode (ctCollectionId, groupId, uuid_[$COLUMN_LENGTH:75$]);
create index IX_1B41BBA6 on WikiNode (ctCollectionId, uuid_[$COLUMN_LENGTH:75$], companyId);

create index IX_96BC058E on WikiPage (ctCollectionId, format[$COLUMN_LENGTH:75$]);
create unique index IX_7164FAAD on WikiPage (ctCollectionId, groupId, uuid_[$COLUMN_LENGTH:75$]);
create unique index IX_C1195518 on WikiPage (ctCollectionId, groupId, version, externalReferenceCode[$COLUMN_LENGTH:75$]);
create index IX_BC4B7FDC on WikiPage (ctCollectionId, nodeId, head, groupId, title[$COLUMN_LENGTH:255$]);
create index IX_5C4F16F3 on WikiPage (ctCollectionId, nodeId, head, resourcePrimKey);
create index IX_F67A73A0 on WikiPage (ctCollectionId, nodeId, head, title[$COLUMN_LENGTH:255$]);
create index IX_3AF5CE2A on WikiPage (ctCollectionId, nodeId, parentTitle[$COLUMN_LENGTH:255$]);
create index IX_2C864038 on WikiPage (ctCollectionId, nodeId, redirectTitle[$COLUMN_LENGTH:255$]);
create unique index IX_B3A439E1 on WikiPage (ctCollectionId, nodeId, resourcePrimKey, version);
create index IX_BAE59638 on WikiPage (ctCollectionId, nodeId, status, groupId, userId);
create index IX_BEF82338 on WikiPage (ctCollectionId, nodeId, status, head, groupId, parentTitle[$COLUMN_LENGTH:255$]);
create index IX_A27F2FFC on WikiPage (ctCollectionId, nodeId, status, head, parentTitle[$COLUMN_LENGTH:255$]);
create index IX_A534290A on WikiPage (ctCollectionId, nodeId, status, head, redirectTitle[$COLUMN_LENGTH:255$]);
create index IX_88A61BED on WikiPage (ctCollectionId, nodeId, status, resourcePrimKey);
create index IX_125CA00E on WikiPage (ctCollectionId, nodeId, status, title[$COLUMN_LENGTH:255$]);
create index IX_98C6DBF4 on WikiPage (ctCollectionId, nodeId, status, userId);
create unique index IX_E6CA66D4 on WikiPage (ctCollectionId, nodeId, title[$COLUMN_LENGTH:255$], version);
create index IX_9D940EBE on WikiPage (ctCollectionId, status, resourcePrimKey);
create index IX_EF67EDB3 on WikiPage (ctCollectionId, uuid_[$COLUMN_LENGTH:75$], companyId);

create unique index IX_DF42DE46 on WikiPageResource (ctCollectionId, nodeId, title[$COLUMN_LENGTH:255$]);
create index IX_CAEEA7E1 on WikiPageResource (ctCollectionId, uuid_[$COLUMN_LENGTH:75$], companyId);
create unique index IX_CA10685B on WikiPageResource (ctCollectionId, uuid_[$COLUMN_LENGTH:75$], groupId);