##
## JBoss
##

    jboss-dir=../../jboss-eap-7.1.0
    jboss-extra.lib.dirs=/modules/system/layers/base/javax/mail,/modules/system/layers/base/javax/persistence,/modules/system/layers/base/javax/servlet,/modules/system/layers/base/javax/transaction
    jboss-global.lib.dir=/modules/com/liferay/portal/main
    jboss-portal.dir=/standalone/deployments/ROOT.war
    jboss-server.detector.server.id=jboss

##
## tc Server
##

    tcserver-dir=../../../../tc-server-4.0.2
    tcserver-extra.lib.dirs=/runtimes/tomcat-9.0.10.A.RELEASE/lib
    tcserver-global.lib.dir=/instances/liferay/lib
    tcserver-portal.dir=/instances/liferay/webapps/ROOT
    tcserver-server.detector.server.id=tomcat

##
## Tomcat
##

    tomcat-dir=../../tomcat-9.0.33
    tomcat-extra.lib.dirs=/bin
    tomcat-global.lib.dir=/lib
    tomcat-portal.dir=/webapps/ROOT
    tomcat-server.detector.server.id=tomcat

##
## WebLogic
##

    weblogic-dir=../../weblogic-12.2.1
    weblogic-extra.lib.dirs=/wlserver/modules
    weblogic-global.lib.dir=/domains/liferay/lib
    weblogic-portal.dir=/domains/liferay/autodeploy/ROOT
    weblogic-server.detector.server.id=weblogic

##
## WebSphere
##

    websphere-dir=../../websphere-9.0.0.0
    websphere-extra.lib.dirs=
    websphere-global.lib.dir=/lib
    websphere-portal.dir=/profiles/liferay/installedApps/liferay-cell/liferay-portal.ear/liferay-portal.war
    websphere-server.detector.server.id=websphere

##
## WildFly
##

    wildfly-dir=../../wildfly-16.0.0
    wildfly-extra.lib.dirs=/modules/system/layers/base/javax/mail,/modules/system/layers/base/javax/persistence,/modules/system/layers/base/javax/servlet,/modules/system/layers/base/javax/transaction
    wildfly-global.lib.dir=/modules/com/liferay/portal/main
    wildfly-portal.dir=/standalone/deployments/ROOT.war
    wildfly-server.detector.server.id=wildfly