dependencies {
	testIntegrationImplementation group: "org.osgi", name: "osgi.core", version: "6.0.0"
	testIntegrationImplementation project(":apps:layout:layout-test-util")
	testIntegrationImplementation project(":apps:portal-configuration:portal-configuration-module-configuration-api")
	testIntegrationImplementation project(":apps:portal:portal-virtual-host-api")
	testIntegrationImplementation project(":test:arquillian-extension-junit-bridge")
}