/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.model.impl;

import com.liferay.portal.tools.service.builder.test.model.ArithmeticEntry;
import com.liferay.portal.tools.service.builder.test.service.ArithmeticEntryLocalServiceUtil;

/**
 * The extended model base implementation for the ArithmeticEntry service. Represents a row in the &quot;ArithmeticEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ArithmeticEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ArithmeticEntryImpl
 * @see ArithmeticEntry
 * @generated
 */
public abstract class ArithmeticEntryBaseImpl
	extends ArithmeticEntryModelImpl implements ArithmeticEntry {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a arithmetic entry model instance should use the <code>ArithmeticEntry</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			ArithmeticEntryLocalServiceUtil.addArithmeticEntry(this);
		}
		else {
			ArithmeticEntryLocalServiceUtil.updateArithmeticEntry(this);
		}
	}

}