/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.tools.service.builder.test.model.ArithmeticEntry;
import com.liferay.portal.tools.service.builder.test.model.ArithmeticEntryModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ArithmeticEntry service. Represents a row in the &quot;ArithmeticEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ArithmeticEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ArithmeticEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ArithmeticEntryImpl
 * @generated
 */
public class ArithmeticEntryModelImpl
	extends BaseModelImpl<ArithmeticEntry> implements ArithmeticEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a arithmetic entry model instance should use the <code>ArithmeticEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "ArithmeticEntry";

	public static final Object[][] TABLE_COLUMNS = {
		{"arithmeticEntryId", Types.BIGINT}, {"number1", Types.BIGINT},
		{"number2", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("arithmeticEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("number1", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("number2", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ArithmeticEntry (arithmeticEntryId LONG not null primary key,number1 LONG,number2 LONG)";

	public static final String TABLE_SQL_DROP = "drop table ArithmeticEntry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY arithmeticEntry.arithmeticEntryId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ArithmeticEntry.arithmeticEntryId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ARITHMETICENTRYID_COLUMN_BITMASK = 1L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.portal.tools.service.builder.test.service.util.ServiceProps.
			get(
				"lock.expiration.time.com.liferay.portal.tools.service.builder.test.model.ArithmeticEntry"));

	public ArithmeticEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _arithmeticEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setArithmeticEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _arithmeticEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ArithmeticEntry.class;
	}

	@Override
	public String getModelClassName() {
		return ArithmeticEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ArithmeticEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ArithmeticEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ArithmeticEntry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ArithmeticEntry)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ArithmeticEntry, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ArithmeticEntry, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ArithmeticEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ArithmeticEntry, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ArithmeticEntry, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<ArithmeticEntry, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<ArithmeticEntry, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<ArithmeticEntry, Object>>();

			attributeGetterFunctions.put(
				"arithmeticEntryId", ArithmeticEntry::getArithmeticEntryId);
			attributeGetterFunctions.put(
				"number1", ArithmeticEntry::getNumber1);
			attributeGetterFunctions.put(
				"number2", ArithmeticEntry::getNumber2);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<ArithmeticEntry, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<ArithmeticEntry, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<ArithmeticEntry, ?>>();

			attributeSetterBiConsumers.put(
				"arithmeticEntryId",
				(BiConsumer<ArithmeticEntry, Long>)
					ArithmeticEntry::setArithmeticEntryId);
			attributeSetterBiConsumers.put(
				"number1",
				(BiConsumer<ArithmeticEntry, Long>)ArithmeticEntry::setNumber1);
			attributeSetterBiConsumers.put(
				"number2",
				(BiConsumer<ArithmeticEntry, Long>)ArithmeticEntry::setNumber2);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getArithmeticEntryId() {
		return _arithmeticEntryId;
	}

	@Override
	public void setArithmeticEntryId(long arithmeticEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_arithmeticEntryId = arithmeticEntryId;
	}

	@Override
	public long getNumber1() {
		return _number1;
	}

	@Override
	public void setNumber1(long number1) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_number1 = number1;
	}

	@Override
	public long getNumber2() {
		return _number2;
	}

	@Override
	public void setNumber2(long number2) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_number2 = number2;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, ArithmeticEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ArithmeticEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ArithmeticEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ArithmeticEntryImpl arithmeticEntryImpl = new ArithmeticEntryImpl();

		arithmeticEntryImpl.setArithmeticEntryId(getArithmeticEntryId());
		arithmeticEntryImpl.setNumber1(getNumber1());
		arithmeticEntryImpl.setNumber2(getNumber2());

		arithmeticEntryImpl.resetOriginalValues();

		return arithmeticEntryImpl;
	}

	@Override
	public ArithmeticEntry cloneWithOriginalValues() {
		ArithmeticEntryImpl arithmeticEntryImpl = new ArithmeticEntryImpl();

		arithmeticEntryImpl.setArithmeticEntryId(
			this.<Long>getColumnOriginalValue("arithmeticEntryId"));
		arithmeticEntryImpl.setNumber1(
			this.<Long>getColumnOriginalValue("number1"));
		arithmeticEntryImpl.setNumber2(
			this.<Long>getColumnOriginalValue("number2"));

		return arithmeticEntryImpl;
	}

	@Override
	public int compareTo(ArithmeticEntry arithmeticEntry) {
		long primaryKey = arithmeticEntry.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ArithmeticEntry)) {
			return false;
		}

		ArithmeticEntry arithmeticEntry = (ArithmeticEntry)object;

		long primaryKey = arithmeticEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ArithmeticEntry> toCacheModel() {
		ArithmeticEntryCacheModel arithmeticEntryCacheModel =
			new ArithmeticEntryCacheModel();

		arithmeticEntryCacheModel.arithmeticEntryId = getArithmeticEntryId();

		arithmeticEntryCacheModel.number1 = getNumber1();

		arithmeticEntryCacheModel.number2 = getNumber2();

		return arithmeticEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ArithmeticEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ArithmeticEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ArithmeticEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((ArithmeticEntry)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ArithmeticEntry>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					ArithmeticEntry.class, ModelWrapper.class);

	}

	private long _arithmeticEntryId;
	private long _number1;
	private long _number2;

	public <T> T getColumnValue(String columnName) {
		Function<ArithmeticEntry, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ArithmeticEntry)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("arithmeticEntryId", _arithmeticEntryId);
		_columnOriginalValues.put("number1", _number1);
		_columnOriginalValues.put("number2", _number2);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("arithmeticEntryId", 1L);

		columnBitmasks.put("number1", 2L);

		columnBitmasks.put("number2", 4L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ArithmeticEntry _escapedModel;

}