/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.tools.service.builder.test.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.tools.service.builder.test.model.NotCachedEntry;
import com.liferay.portal.tools.service.builder.test.model.NotCachedEntryModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the NotCachedEntry service. Represents a row in the &quot;NotCachedEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>NotCachedEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link NotCachedEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see NotCachedEntryImpl
 * @generated
 */
public class NotCachedEntryModelImpl
	extends BaseModelImpl<NotCachedEntry> implements NotCachedEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a not cached entry model instance should use the <code>NotCachedEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "NotCachedEntry";

	public static final Object[][] TABLE_COLUMNS = {
		{"nestedSetsTreeEntryId", Types.BIGINT}, {"column1", Types.BIGINT},
		{"column2", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("nestedSetsTreeEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("column1", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("column2", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table NotCachedEntry (nestedSetsTreeEntryId LONG not null primary key,column1 LONG,column2 LONG)";

	public static final String TABLE_SQL_DROP = "drop table NotCachedEntry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY notCachedEntry.nestedSetsTreeEntryId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY NotCachedEntry.nestedSetsTreeEntryId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long COLUMN1_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long COLUMN2_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)
	 */
	@Deprecated
	public static final long NESTEDSETSTREEENTRYID_COLUMN_BITMASK = 4L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.portal.tools.service.builder.test.service.util.ServiceProps.
			get(
				"lock.expiration.time.com.liferay.portal.tools.service.builder.test.model.NotCachedEntry"));

	public NotCachedEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _nestedSetsTreeEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setNestedSetsTreeEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _nestedSetsTreeEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return NotCachedEntry.class;
	}

	@Override
	public String getModelClassName() {
		return NotCachedEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<NotCachedEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<NotCachedEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<NotCachedEntry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((NotCachedEntry)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<NotCachedEntry, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<NotCachedEntry, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(NotCachedEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<NotCachedEntry, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<NotCachedEntry, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, NotCachedEntry>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			NotCachedEntry.class.getClassLoader(), NotCachedEntry.class,
			ModelWrapper.class);

		try {
			Constructor<NotCachedEntry> constructor =
				(Constructor<NotCachedEntry>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<NotCachedEntry, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<NotCachedEntry, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<NotCachedEntry, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<NotCachedEntry, Object>>();
		Map<String, BiConsumer<NotCachedEntry, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<NotCachedEntry, ?>>();

		attributeGetterFunctions.put(
			"nestedSetsTreeEntryId", NotCachedEntry::getNestedSetsTreeEntryId);
		attributeSetterBiConsumers.put(
			"nestedSetsTreeEntryId",
			(BiConsumer<NotCachedEntry, Long>)
				NotCachedEntry::setNestedSetsTreeEntryId);
		attributeGetterFunctions.put("column1", NotCachedEntry::getColumn1);
		attributeSetterBiConsumers.put(
			"column1",
			(BiConsumer<NotCachedEntry, Long>)NotCachedEntry::setColumn1);
		attributeGetterFunctions.put("column2", NotCachedEntry::getColumn2);
		attributeSetterBiConsumers.put(
			"column2",
			(BiConsumer<NotCachedEntry, Long>)NotCachedEntry::setColumn2);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getNestedSetsTreeEntryId() {
		return _nestedSetsTreeEntryId;
	}

	@Override
	public void setNestedSetsTreeEntryId(long nestedSetsTreeEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nestedSetsTreeEntryId = nestedSetsTreeEntryId;
	}

	@Override
	public long getColumn1() {
		return _column1;
	}

	@Override
	public void setColumn1(long column1) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_column1 = column1;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalColumn1() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("column1"));
	}

	@Override
	public long getColumn2() {
		return _column2;
	}

	@Override
	public void setColumn2(long column2) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_column2 = column2;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalColumn2() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("column2"));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (entry.getValue() != getColumnValue(entry.getKey())) {
				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, NotCachedEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public NotCachedEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, NotCachedEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		NotCachedEntryImpl notCachedEntryImpl = new NotCachedEntryImpl();

		notCachedEntryImpl.setNestedSetsTreeEntryId(getNestedSetsTreeEntryId());
		notCachedEntryImpl.setColumn1(getColumn1());
		notCachedEntryImpl.setColumn2(getColumn2());

		notCachedEntryImpl.resetOriginalValues();

		return notCachedEntryImpl;
	}

	@Override
	public int compareTo(NotCachedEntry notCachedEntry) {
		long primaryKey = notCachedEntry.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof NotCachedEntry)) {
			return false;
		}

		NotCachedEntry notCachedEntry = (NotCachedEntry)object;

		long primaryKey = notCachedEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<NotCachedEntry> toCacheModel() {
		NotCachedEntryCacheModel notCachedEntryCacheModel =
			new NotCachedEntryCacheModel();

		notCachedEntryCacheModel.nestedSetsTreeEntryId =
			getNestedSetsTreeEntryId();

		notCachedEntryCacheModel.column1 = getColumn1();

		notCachedEntryCacheModel.column2 = getColumn2();

		return notCachedEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<NotCachedEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<NotCachedEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<NotCachedEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((NotCachedEntry)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<NotCachedEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<NotCachedEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<NotCachedEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((NotCachedEntry)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, NotCachedEntry>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _nestedSetsTreeEntryId;
	private long _column1;
	private long _column2;

	public <T> T getColumnValue(String columnName) {
		Function<NotCachedEntry, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((NotCachedEntry)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put(
			"nestedSetsTreeEntryId", _nestedSetsTreeEntryId);
		_columnOriginalValues.put("column1", _column1);
		_columnOriginalValues.put("column2", _column2);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("nestedSetsTreeEntryId", 1L);

		columnBitmasks.put("column1", 2L);

		columnBitmasks.put("column2", 4L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private NotCachedEntry _escapedModel;

}