<?xml version="1.0"?>

<project basedir="." default="run" name="benchmarks" xmlns:if="ant:if" xmlns:unless="ant:unless">
	<import file="../build-common.xml" />

	<target name="build-sample-sql">
		<gradle-execute dir="../modules/util/portal-tools-sample-sql-builder" task="jar" />

		<path id="sample.sql.builder.classpath">
			<fileset
				dir="${sdk.dir}/dist"
				includes="com.liferay.blogs.*.jar"
			/>
			<fileset
				dir="${sdk.dir}/dist"
				includes="com.liferay.commerce.*.jar"
			/>
			<fileset
				dir="${sdk.dir}/dist"
				includes="com.liferay.dynamic.data.*.jar"
			/>
			<fileset
				dir="${sdk.dir}/dist"
				includes="com.liferay.fragment.*.jar"
			/>
			<fileset
				dir="${sdk.dir}/dist"
				includes="com.liferay.friendly.url.*.jar"
			/>
			<fileset
				dir="${sdk.dir}/dist"
				includes="com.liferay.journal.*.jar"
			/>
			<fileset
				dir="${sdk.dir}/dist"
				includes="com.liferay.layout.*.jar"
			/>
			<fileset
				dir="${sdk.dir}/dist"
				includes="com.liferay.message.boards.*.jar"
			/>
			<fileset
				dir="${sdk.dir}/dist"
				includes="com.liferay.portal.tools.sample.sql.builder*.jar"
			/>
			<fileset
				dir="${sdk.dir}/dist"
				includes="com.liferay.subscription.*.jar"
			/>

			<fileset
				dir="${sdk.dir}/dist"
				includes="com.liferay.view.count.*.jar"
			/>

			<fileset
				dir="${sdk.dir}/dist"
				includes="com.liferay.wiki.*.jar"
			/>
			<path refid="project.classpath" />
		</path>

		<available file="benchmarks.${user.name}.properties" property="user.properites.avaiable" />
		<available file="benchmarks.${env.COMPUTERNAME}.properties" property="env.computer.name.properites.avaiable" />
		<available file="benchmarks.${env.HOST}.properties" property="env.host.properites.avaiable" />
		<available file="benchmarks.${env.HOSTNAME}.properties" property="env.host.name.properites.avaiable" />

		<property if:true="${user.properites.avaiable}" name="sample.sql.properties.file" value="benchmarks.${user.name}.properties" />
		<property if:true="${env.computer.name.properites.avaiable}" name="sample.sql.properties.file" value="benchmarks.${env.COMPUTERNAME}.properties" />
		<property if:true="${env.host.properites.avaiable}" name="sample.sql.properties.file" value="benchmarks.${env.HOST}.properties" />
		<property if:true="${env.host.name.properites.avaiable}" name="sample.sql.properties.file" value="benchmarks.${env.HOSTNAME}.properties" />
	
		<if>
			<and>
				<equals arg1="${user.properites.avaiable}" arg2="false" />
				<equals arg1="${env.computer.name.properites.avaiable}" arg2="false" />
				<equals arg1="${env.host.properites.avaiable}" arg2="false" />
				<equals arg1="${env.host.name.properites.avaiable}" arg2="false" />
			</and>
			<then>
				<property name="sample.sql.properties.file" value="benchmarks.properties" />
			</then>
		</if>

		<java
			classname="com.liferay.portal.tools.sample.sql.builder.SampleSQLBuilder"
			classpathref="sample.sql.builder.classpath"
		>
			<sysproperty key="external-properties" value="com/liferay/portal/tools/dependencies/portal-tools.properties" />
			<sysproperty key="sample-sql-properties" value="${sample.sql.properties.file}" />
		</java>
	</target>

	<target name="clean">
		<delete includeemptydirs="true">
			<fileset
				dir="."
				includes="*.csv,*.sql,benchmarks-actual.properties,output/**,temp/**"
			/>
		</delete>
	</target>
</project>